### ISSUE TITLE
Make it for Julia stable release?

### ISSUE THREAD

**Issue by camilogarciabotero** [jolin-io/JuliaScript.jl#4] opened 2024-02-14 06:03 UTC
Hi all,

Thanks for working on this package. I was wondering if there is any chance to make it compatible with more Julia versions. I noticed that it only works for Julia 1.6 (according to the `Project.toml`), could it be possible to expand the range of Julia versions to work with?

Best.

**Comment by adamnovak** [comment] 2024-04-17 22:59
It seems to be working fine on Julia 1.10 for me.

**Comment by schlichtanders** [comment] 2024-04-18 09:54
the semantic version interpretation of a project.toml entry of "1.6" means at least "1.6" and everything compatible with "1". 

If it would have been "1.6.0" it means at least "1.6.0" and everything compatible with "1.6".

Closing this as it seems to work as intended for all recent julia versions

**Closed by schlichtanders** 2024-04-18 09:54 UTC
